# Generated by Django 2.2.10 on 2021-07-31 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='many_choice',
            field=models.ManyToManyField(null=True, to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='one_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_one_choice', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='self_text',
            field=models.TextField(null=True),
        ),
    ]
