# Generated by Django 2.2.10 on 2021-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210731_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='time_finish',
            field=models.DateTimeField(verbose_name='Дата завершения опроса'),
        ),
    ]
