# Generated by Django 2.2.10 on 2021-07-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210731_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='name',
            new_name='text',
        ),
    ]
